(cl:defpackage jointControl-srv
  (:use )
  (:export
   "BROADCASTTAGFRAME"
   "<BROADCASTTAGFRAME-REQUEST>"
   "BROADCASTTAGFRAME-REQUEST"
   "<BROADCASTTAGFRAME-RESPONSE>"
   "BROADCASTTAGFRAME-RESPONSE"
   "ROBOTMOVE"
   "<ROBOTMOVE-REQUEST>"
   "ROBOTMOVE-REQUEST"
   "<ROBOTMOVE-RESPONSE>"
   "ROBOTMOVE-RESPONSE"
  ))

