// Generated by gencpp from file robotic_arm/joint_position_array.msg
// DO NOT EDIT!


#ifndef ROBOTIC_ARM_MESSAGE_JOINT_POSITION_ARRAY_H
#define ROBOTIC_ARM_MESSAGE_JOINT_POSITION_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotic_arm/joint_position.h>

namespace robotic_arm
{
template <class ContainerAllocator>
struct joint_position_array_
{
  typedef joint_position_array_<ContainerAllocator> Type;

  joint_position_array_()
    : data()  {
    }
  joint_position_array_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robotic_arm::joint_position_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robotic_arm::joint_position_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robotic_arm::joint_position_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotic_arm::joint_position_array_<ContainerAllocator> const> ConstPtr;

}; // struct joint_position_array_

typedef ::robotic_arm::joint_position_array_<std::allocator<void> > joint_position_array;

typedef boost::shared_ptr< ::robotic_arm::joint_position_array > joint_position_arrayPtr;
typedef boost::shared_ptr< ::robotic_arm::joint_position_array const> joint_position_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotic_arm::joint_position_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotic_arm::joint_position_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotic_arm::joint_position_array_<ContainerAllocator1> & lhs, const ::robotic_arm::joint_position_array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotic_arm::joint_position_array_<ContainerAllocator1> & lhs, const ::robotic_arm::joint_position_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotic_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotic_arm::joint_position_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotic_arm::joint_position_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_arm::joint_position_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_arm::joint_position_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_arm::joint_position_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_arm::joint_position_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotic_arm::joint_position_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f6cb9944d2c5ab5cff8aff4ba87d255";
  }

  static const char* value(const ::robotic_arm::joint_position_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f6cb9944d2c5ab5ULL;
  static const uint64_t static_value2 = 0xcff8aff4ba87d255ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotic_arm::joint_position_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotic_arm/joint_position_array";
  }

  static const char* value(const ::robotic_arm::joint_position_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotic_arm::joint_position_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint_position[] data\n"
"\n"
"================================================================================\n"
"MSG: robotic_arm/joint_position\n"
"float32[] data\n"
;
  }

  static const char* value(const ::robotic_arm::joint_position_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotic_arm::joint_position_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_position_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotic_arm::joint_position_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotic_arm::joint_position_array_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robotic_arm::joint_position_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIC_ARM_MESSAGE_JOINT_POSITION_ARRAY_H
