// Generated by gencpp from file jointControl/RobotMove.msg
// DO NOT EDIT!


#ifndef JOINTCONTROL_MESSAGE_ROBOTMOVE_H
#define JOINTCONTROL_MESSAGE_ROBOTMOVE_H

#include <ros/service_traits.h>


#include <jointControl/RobotMoveRequest.h>
#include <jointControl/RobotMoveResponse.h>


namespace jointControl
{

struct RobotMove
{

typedef RobotMoveRequest Request;
typedef RobotMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMove
} // namespace jointControl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jointControl::RobotMove > {
  static const char* value()
  {
    return "fca097bf97be1a76fa923cfcb956b244";
  }

  static const char* value(const ::jointControl::RobotMove&) { return value(); }
};

template<>
struct DataType< ::jointControl::RobotMove > {
  static const char* value()
  {
    return "jointControl/RobotMove";
  }

  static const char* value(const ::jointControl::RobotMove&) { return value(); }
};


// service_traits::MD5Sum< ::jointControl::RobotMoveRequest> should match
// service_traits::MD5Sum< ::jointControl::RobotMove >
template<>
struct MD5Sum< ::jointControl::RobotMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jointControl::RobotMove >::value();
  }
  static const char* value(const ::jointControl::RobotMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jointControl::RobotMoveRequest> should match
// service_traits::DataType< ::jointControl::RobotMove >
template<>
struct DataType< ::jointControl::RobotMoveRequest>
{
  static const char* value()
  {
    return DataType< ::jointControl::RobotMove >::value();
  }
  static const char* value(const ::jointControl::RobotMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jointControl::RobotMoveResponse> should match
// service_traits::MD5Sum< ::jointControl::RobotMove >
template<>
struct MD5Sum< ::jointControl::RobotMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jointControl::RobotMove >::value();
  }
  static const char* value(const ::jointControl::RobotMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jointControl::RobotMoveResponse> should match
// service_traits::DataType< ::jointControl::RobotMove >
template<>
struct DataType< ::jointControl::RobotMoveResponse>
{
  static const char* value()
  {
    return DataType< ::jointControl::RobotMove >::value();
  }
  static const char* value(const ::jointControl::RobotMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JOINTCONTROL_MESSAGE_ROBOTMOVE_H
