// Generated by gencpp from file jointControl/RobotMoveResponse.msg
// DO NOT EDIT!


#ifndef JOINTCONTROL_MESSAGE_ROBOTMOVERESPONSE_H
#define JOINTCONTROL_MESSAGE_ROBOTMOVERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jointControl
{
template <class ContainerAllocator>
struct RobotMoveResponse_
{
  typedef RobotMoveResponse_<ContainerAllocator> Type;

  RobotMoveResponse_()
    : success(false)  {
    }
  RobotMoveResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::jointControl::RobotMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jointControl::RobotMoveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMoveResponse_

typedef ::jointControl::RobotMoveResponse_<std::allocator<void> > RobotMoveResponse;

typedef boost::shared_ptr< ::jointControl::RobotMoveResponse > RobotMoveResponsePtr;
typedef boost::shared_ptr< ::jointControl::RobotMoveResponse const> RobotMoveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jointControl::RobotMoveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jointControl::RobotMoveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jointControl::RobotMoveResponse_<ContainerAllocator1> & lhs, const ::jointControl::RobotMoveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jointControl::RobotMoveResponse_<ContainerAllocator1> & lhs, const ::jointControl::RobotMoveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jointControl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jointControl::RobotMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jointControl::RobotMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jointControl::RobotMoveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::jointControl::RobotMoveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jointControl/RobotMoveResponse";
  }

  static const char* value(const ::jointControl::RobotMoveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::jointControl::RobotMoveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotMoveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jointControl::RobotMoveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jointControl::RobotMoveResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOINTCONTROL_MESSAGE_ROBOTMOVERESPONSE_H
